/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ConnectionTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "LtApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LtApiUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Server": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "WebsocketApi": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "ZenQuoteApiUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}