name: CI/CD

on:
  push:
    branches: [main]

jobs:
  ci-cd:
    name: CI/CD Process
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.5

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: arn:aws:iam::296062572585:role/lt-showcase-production-github
      #     aws-region: us-east-1

      - name: Run linting
        run: make lint

      - name: Run type checking
        run: make typecheck

      - name: Run testing
        run: make test

      # - name: Deploy
      #   if: github.event_name == 'push' && (github.ref == 'refs/heads/main')
      #   run: make deploy
